### ISSUE TITLE
Adicionar conceitos da disciplina no jogo: capítulos 1, 2, 3 e 6

### ISSUE THREAD

**Issue by Dalianelima** [OQuartetoFantastico/jogo-web#13]
Baseado em #1 e #9:
- [x] Código de linha
- [x] Categorias do cabeamento estruturado
- [x]  Par metálico UTP
- [x]  Fibras mono e multimodo

**Comment by Hazzkunho** [comment]
Hoje mesmo o index.html foi "updateado" com a primeira sala do jogo, contendo um enigma envolvendo códigos de linha.

**Comment by Hazzkunho** [comment]
Na confecção do segundo enigma, há a presença do conceito de diafonia como um ruído de imagem.
Na segunda sala de enigma do jogo há um nove que se parece muito com seis, feito de forma proposital para enganar o jogador

**Comment by Hazzkunho** [comment]
Ainda no segundo enigma, o pato faz um comentário sobre os cabos de fibra multimodo e monomodo, é para ser visto como mais um dos delírios do pato.
