### ISSUE TITLE
Estudar exemplos de jogos com Twine

### ISSUE THREAD

**Issue by Dalianelima** [OQuartetoFantastico/jogo-web#2]
Plano de Dominação Mundial: [https://pdm.boidacarapreta.cc/](url) e [https://github.com/boidacarapreta/pdm](url)
Registro de um Sobrevivente: [https://arc20201.boidacarapreta.cc/](url) e [https://github.com/boidacarapreta/pdm](url)

**Comment by Hazzkunho** [comment]
Como inspiração, estamos usando como exemplos os seguintes jogos:

-Phoenix Wright: Ace Attorney
-Danganronpa
-Doki Doki Literature Club
