### ISSUE TITLE
Estudar conteúdo multimídia: setores do cabeamento estruturado

### ISSUE THREAD

**Issue by Dalianelima** [OQuartetoFantastico/jogo-web#21]
Estudar como tornar o jogo mais interessante: jogabilidade, complexidade, multimídia, etc.

**Comment by Hazzkunho** [comment]
- [x] Fazer artes do segundo Enigma
- [x] Fazer artes do terceiro Enigma
- [x] Fazer artes de um possível quarto Enigma
- [x] Adicionar mais sprites pro maldito pato de borracha

**Comment by Hazzkunho** [comment]
Só adicionando aqui como uma pequena observação, as artes do primeiro enigma estão feitas.

**Comment by Hazzkunho** [comment]
A esmagadora maioria das artes estão feitas.
