### ISSUE TITLE
Definir o Jogo

### ISSUE THREAD

**Issue by Dalianelima** [OQuartetoFantastico/jogo-web#7]
- [x] Referências: literatura, mídias em geral e outros jogos
- [x] Roteiro: primeiros passos da aventura
- [x] Personagens: perfis, evolução
- [x] Artefatos: armas, poções etc.
- [x] Mundo/universo

**Comment by Hazzkunho** [comment]
As referências para o jogo são:
-Danganronpa
-Doki Doki Literature Club
-Phoenix Wright: Ace Attorney

Seria no nosso universo atual mesmo, e o personagem seria a própria pessoa que estaria jogando.
